[workspace]
resolver = "3"
members = ["crates/fast-down", "crates/fast-pull", "crates/fast-steal"]

[workspace.package]
authors = ["share121 <me@s121.top>", "Cyan Changes <contact@cyans.me>"]
edition = "2024"
homepage = "https://github.com/fast-down/core"
repository = "https://github.com/fast-down/core"
license = "MIT"

[workspace.dependencies]
bytes = { version = "1.10.1", default-features = false }
fast-pull = { path = "crates/fast-pull", version = "3.5.0" }
fast-steal = { path = "crates/fast-steal", version = "6.2.0" }
futures = { version = "0.3.31", default-features = false }
kanal = "0.1.1"
spin = { version = "0.10.0", default-features = false, features = [
  "spin_mutex",
] }
thiserror = "2.0.12"
url = "2.5.4"
