[package]
name = "fast-down"
description = "Download everything fast"
version = "3.2.0"
readme = "README.md"
documentation = "https://docs.rs/fast-down"
keywords = ["download", "fast", "parallel", "concurrency"]
categories = ["concurrency", "asynchronous", "network-programming", "no-std"]
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
fast-pull.workspace = true
futures.workspace = true
url.workspace = true
content_disposition = { version = "0.4.0", optional = true }
urlencoding = { version = "2.1.3", optional = true }
bytes.workspace = true
reqwest = { version = "0.12.22", default-features = false, features = [
  "stream",
], optional = true }
kanal.workspace = true
log = "0.4.27"
reqwest-middleware = { version = "0.4.2", optional = true }
thiserror.workspace = true

[features]
default = ["reqwest-middleware"]
reqwest = ["dep:reqwest", "dep:content_disposition", "dep:urlencoding"]
reqwest-middleware = ["reqwest", "dep:reqwest-middleware"]

[dev-dependencies]
tokio = { version = "1.47.1", features = [
  "rt",
  "io-util",
  "test-util",
], default-features = false }
mockito = "1.7.0"
