[package]
name = "fast-down"
version = "3.5.1"
authors.workspace = true
edition.workspace = true
description = "Download everything fast"
documentation = "https://docs.rs/fast-down"
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["concurrency", "download", "fast", "parallel"]
categories = ["asynchronous", "concurrency", "network-programming", "no-std"]

[dependencies]
bytes.workspace = true
content_disposition = { version = "0.4.0", optional = true }
fast-pull.workspace = true
futures.workspace = true
httpdate = { version = "1.0.3", optional = true }
inherit-config = { version = "0.1.1", optional = true }
inherit-config-derive = { version = "0.1.1", optional = true }
parking_lot = { workspace = true, optional = true }
reqwest = { version = "0.13.1", default-features = false, optional = true }
sanitize-filename = { version = "0.6.0", optional = true }
thiserror = { workspace = true, optional = true }
tokio = { version = "1.49.0", default-features = false }
url.workspace = true
urlencoding = { version = "2.1.3", optional = true }

[dev-dependencies]
mockito = "1.7.1"
tokio = { version = "1.49.0", default-features = false, features = [
  "io-util",
  "rt",
  "test-util",
] }

[features]
http = [
  "dep:content_disposition",
  "dep:parking_lot",
  "dep:thiserror",
  "dep:urlencoding"
]
reqwest = ["dep:httpdate", "dep:reqwest", "http"]
sanitize-filename = ["dep:sanitize-filename"]
utils = [
  "dep:inherit-config",
  "dep:inherit-config-derive",
  "reqwest",
  "reqwest/default-tls",
]
