[package]
name = "fast-down"
description = "Download everything fast"
version = "3.2.7"
readme = "README.md"
documentation = "https://docs.rs/fast-down"
keywords = ["download", "fast", "parallel", "concurrency"]
categories = ["concurrency", "asynchronous", "network-programming", "no-std"]
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
fast-pull.workspace = true
futures.workspace = true
url.workspace = true
content_disposition = { version = "0.4.0", optional = true }
urlencoding = { version = "2.1.3", optional = true }
bytes.workspace = true
reqwest = { version = "0.12.22", default-features = false, optional = true }
thiserror.workspace = true
tokio = { version = "1.47.1", default-features = false }
httpdate = { version = "1.0.3", optional = true }
spin.workspace = true

[features]
default = ["reqwest"]
http = ["dep:content_disposition", "dep:urlencoding"]
reqwest = ["http", "dep:reqwest", "dep:httpdate"]

[dev-dependencies]
tokio = { version = "1.47.1", features = [
  "rt",
  "io-util",
  "test-util",
], default-features = false }
mockito = "1.7.0"
